### PR TITLE
fix undici issue with build and package to binary

### PR DESCRIPTION
**Pull request by motdotla**
received error:

```
➜  multiple dotenvx run -- node index.js
pkg/prelude/bootstrap.js:1872
      throw error;
      ^

ReferenceError: ReadableStream is not defined
    at Object.<anonymous> (/snapshot/dotenvx/node_modules/undici/lib/fetch/response.js:507:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._compile (pkg/prelude/bootstrap.js:1933:32)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/snapshot/dotenvx/node_modules/undici/lib/fetch/index.js:11:5)
```

downgraded to undici 5

### CODE REVIEW

**Comment by motdotla** [comment]
probably related: https://github.com/mswjs/msw/discussions/1934

@SuperchupuDev fyi, i had to downgrade undici to 5

**Comment by SuperchupuDev** [comment]
oh yeah, i forgot to mention undici 6 requires at least node 18. apparently node versions <18 are end of life (they stopped support for node 16 earlier than usual). whether to use undici 6 (and with that requiring users to use node 18 or above) or 5 is up to you, i don't know if undici 5 has serious tradeoffs compared to 6

**Comment by motdotla** [comment]
ok, i'll see if we can do that. we've been packaging to node 16. i think we tried a newer version but then ran into issues with our packager - https://github.com/vercel/pkg

will give it a shot and if doesn't work, i might look into packaging with deno instead.

**Comment by SuperchupuDev** [comment]
another update: it looks like jest, which is used in this project, can mess up some global variables when running tests which breaks undici 6. one solution (if you end up deciding to switch to undici 6) could be to switch to a better test runner such as [vitest](https://vitest.dev/)

**Pull request merged**
