### PR TITLE
replace `@inquirer/confirm` and `ora`

### PR DESCRIPTION
**Pull request by SuperchupuDev**
- Replaces `@inquirer/confirm` ([27](https://npmgraph.js.org/?q=@inquirer/confirm@2) subdependencies) with `@clack/core` ([2](https://npmgraph.js.org/?q=%40clack%2Fcore))
- Replaces `ora` ([29](https://npmgraph.js.org/?q=ora@5.4.1) subdependencies) with a native alternative (0) based on logic provided by @PondWader

As such, this PR makes the total number of dependencies used by dotenvx go from [131](https://npmgraph.js.org/?q=@dotenvx/dotenvx@1.3.0) to just [99](https://npmgraph.js.org/?q=https%3A%2F%2Fraw.githubusercontent.com%2FSuperchupuDev%2Fdotenvx%2F08e88905aa3c21487fba953348e91672ff9243c5%2Fpackage.json) :O

Before:
image

After:
image

### CODE REVIEW

**Comment by SuperchupuDev** [comment]
hold on trying to add tests

**Comment by SuperchupuDev** [comment]
@motdotla tests are failing because of not having 100% coverage but it doesn't show uncovered lines #?
image

**Comment by motdotla** [comment]
maybe related to the double export?

```
module.exports = createSpinner
module.exports.SpinnerClassTestsOnly = Spinner
```

can we avoid having a separate export just for tests? generally a code smell doing that.

**Comment by SuperchupuDev** [comment]
i made it `module.exports = { createSpinner, Spinner }` instead, but it still shows the same

**Comment by SuperchupuDev** [comment]
found it
image

**Comment by motdotla** [comment]
ok, i'll try and take a look later.

are these only part of the `hub` functions? if so, we might just rip out completely - but first i need to move `hub` to its own published extension.

i'm leaning toward keeping http calls out of this library completely and devs will install additional extensions for this kind of functionality. also hub is deprecated and will be replaced by pro.

**Comment by SuperchupuDev** [comment]
coverage is now 100%, but the suite is still failing somehow
image

**Comment by SuperchupuDev** [comment]
> ok, i'll try and take a look later.
> 
> are these only part of the `hub` functions? if so, we might just rip out completely - but first i need to move `hub` to its own published extension.
> 
> i'm leaning toward keeping http calls out of this library completely and devs will install additional extensions for this kind of functionality. also hub is deprecated and will be replaced by pro.

not quite, the spinner is used in more places, but `confirm` is only used in hub

**Comment by motdotla** [comment]
maybe try testing by hand - if you haven't already? i vaguely remember us running into production issues when removing ora and/or confirm. maybe that was in dotenv-vault though. this feels familiar though.

**Comment by SuperchupuDev** [comment]
found it! using setImmediate made it log to the tap file itself, messing up the tap parser

**Comment by SuperchupuDev** [comment]
fixed 🎉 wow tests are hard

**Pull request merged**
