### PR TITLE
Fix: dotenvx precommit hook should check subfolders

### PR DESCRIPTION
**Pull request by MykalMachon**
## What does this PR include?
This PR includes a fix to #333 which includes more context on the overall issue.

I used the [`Ls` class in `src/lib/services/ls.js`](https://github.com/dotenvx/dotenvx/blob/main/src/lib/services/ls.js) to find all the `.env*` files in the repository as part of the precommit hook. If any of these files are not encrypted the pre-commit hook will throw. 

The fix was actually pretty easy to implement, I just had to fight with the tests for awhile 😅
Let me know if there's anything else I should clean up before we can merge.

### CODE REVIEW

**Comment by motdotla** [comment]
thanks @MykalMachon ! just run `npm run standard:fix` to convert to standard formatting and this PR is ready.

**Comment by motdotla** [comment]
actually, i'll take care of that. merging now. thank you! this will be huge for so many people!

**Comment by motdotla** [comment]
released as `1.10.1`

**Comment by motdotla** [comment]
hmm @MykalMachon, maybe we went too aggresive:

```
[dotenvx@1.10.3][precommit] tests/.env not encrypted (or not gitignored)
```

image

now i can't commit to dotenvx with its own precommit 🤣

because tests/**/.env*

**Comment by MykalMachon** [comment]
Argh @motdotla , I don't know why I didn't think of this when testing.
I'm wondering if there's a way we could add a flag to `dotenvx ext precommit --install` that would allow you to set "paths to exclude" in the pre-commit hook? 

For example: 
```bash
dotenvx ext precommit --install --ignore-path "tests/**/*"
```

and that would simply set the pre-commit hook command to be 

```bash
dotenvx ext precommit --ignore-path "tests/**/*"
```

This would ignore any .env files in your repository that match the ignore-path regex string? 
I'm open to other possibilities here, any ideas?

**Pull request merged**
