### PR TITLE
feat(conventions): add mono repo convention

### PR DESCRIPTION
**Pull request by eheyder**
- Refactor conventions to support easy addition of  new conventions
- Add mono convention to support sharing of environment files from parent directories

### CODE REVIEW

**Comment by motdotla** [comment]
looks pretty good. thank you. which monorepos use this convention?

**Comment by eheyder** [comment]
> looks pretty good. thank you. which monorepos use this convention?

There isn't a current mono repo that uses this solution, but is a standard I believe makes sense based to implement for mono repos. This is loosely based on [dotenv-mono](https://www.npmjs.com/package/dotenv-mono) with the addition of merging the dotenv files together.

The solution is targeted for enterprise solutions that would share environment variables between different packages inside the same mono repo. The base example would be a `DOMAIN` environment variable defined for a `website` and `server` package in the same mono repo to support CORS.

**Comment by motdotla** [comment]
ok, let me mull this one over for a while. i'm hesitant to add a convention if it's not really a convention. 

i might move to an extension instead.

**Comment by eheyder** [comment]
I am going to close this out, after considering the changes I believe this is not a good standard to implement. A more robust solution might be to allow for a configuration file to be specified to allow for the same options to be used without having a long command line entry.

**Comment by motdotla** [comment]
ok, if others come across this issue please leave your thoughts. i do like the idea of adding more conventions, but i want to make sure they are fairly popular and battle-tested conventions. nextjs' is the only one i'm currently aware of.

also this PR improved on the code around this so we will bring back if/when we add more conventions.

**Pull request closed without merging**
